SELECT*FROM PRACTICAS
SELECT*FROM ESTUDIANTES
PRACTICAS
SET SQL_SAFE_UPDATES = 0;

select* FROM EMPRESAS
select* FROM TUTORES

CREATE VIEW  PracticasGLOBAL_con_estado AS

SELECT PRACTICAS.id_practica,ESTUDIANTES.nombre ,EMPRESAS.nombre AS empresa,PRACTICAS.horas,PRACTICAS.fecha,PRACTICAS.descripcion,PRACTICAS.estado,TUTORES.nombre AS tutor FROM PRACTICAS 
INNER JOIN EMPRESAS ON PRACTICAS.id_empresa=EMPRESAS.id_empresa
INNER JOIN ESTUDIANTES ON PRACTICAS.id_estudiante=ESTUDIANTES.id_estudiante
INNER JOIN TUTORES ON PRACTICAS.id_tutor=TUTORES.id_tutor


CREATE VIEW PracticasGLOBAL AS

SELECT PRACTICAS.id_practica,ESTUDIANTES.nombre ,EMPRESAS.nombre AS empresa,PRACTICAS.horas,PRACTICAS.fecha,PRACTICAS.descripcion,TUTORES.nombre AS tutor FROM PRACTICAS 
INNER JOIN EMPRESAS ON PRACTICAS.id_empresa=EMPRESAS.id_empresa
INNER JOIN ESTUDIANTES ON PRACTICAS.id_estudiante=ESTUDIANTES.id_estudiante
INNER JOIN TUTORES ON PRACTICAS.id_tutor=TUTORES.id_tutor
 

CREATE VIEW Practicaspendientes AS

SELECT PRACTICAS.id_practica,ESTUDIANTES.nombre ,EMPRESAS.nombre AS empresa,PRACTICAS.horas,PRACTICAS.fecha,PRACTICAS.descripcion,TUTORES.nombre AS tutor FROM PRACTICAS 
INNER JOIN EMPRESAS ON PRACTICAS.id_empresa=EMPRESAS.id_empresa
INNER JOIN ESTUDIANTES ON PRACTICAS.id_estudiante=ESTUDIANTES.id_estudiante
INNER JOIN TUTORES ON PRACTICAS.id_tutor=TUTORES.id_tutor
WHERE PRACTICAS.estado=0


CREATE VIEW Practicasaprobadas AS
SELECT PRACTICAS.id_practica,ESTUDIANTES.nombre ,EMPRESAS.nombre AS empresa,PRACTICAS.horas,PRACTICAS.fecha,PRACTICAS.descripcion,TUTORES.nombre AS tutor FROM PRACTICAS 

INNER JOIN EMPRESAS ON PRACTICAS.id_empresa=EMPRESAS.id_empresa
INNER JOIN ESTUDIANTES ON PRACTICAS.id_estudiante=ESTUDIANTES.id_estudiante
INNER JOIN TUTORES ON PRACTICAS.id_tutor=TUTORES.id_tutor
WHERE PRACTICAS.estado=1


 

