SELECT*FROM PracticasGLOBAL_con_estado

CREATE VIEW PracticasGLOBAL AS

SELECT PRACTICAS.id_practica,ESTUDIANTES.nombre ,EMPRESAS.nombre AS empresa,PRACTICAS.horas,PRACTICAS.fecha,PRACTICAS.descripcion,TUTORES.nombre AS tutor FROM PRACTICAS 
INNER JOIN EMPRESAS ON PRACTICAS.id_empresa=EMPRESAS.id_empresa
INNER JOIN ESTUDIANTES ON PRACTICAS.id_estudiante=ESTUDIANTES.id_estudiante
INNER JOIN TUTORES ON PRACTICAS.id_tutor=TUTORES.id_tutor
 

CREATE VIEW Practicaspendientes AS

SELECT PRACTICAS.id_practica,ESTUDIANTES.nombre ,EMPRESAS.nombre AS empresa,PRACTICAS.horas,PRACTICAS.fecha,PRACTICAS.descripcion,TUTORES.nombre AS tutor FROM PRACTICAS 
INNER JOIN EMPRESAS ON PRACTICAS.id_empresa=EMPRESAS.id_empresa
INNER JOIN ESTUDIANTES ON PRACTICAS.id_estudiante=ESTUDIANTES.id_estudiante
INNER JOIN TUTORES ON PRACTICAS.id_tutor=TUTORES.id_tutor
WHERE PRACTICAS.estado=0


CREATE VIEW Practicasaprobadas AS
SELECT PRACTICAS.id_practica,ESTUDIANTES.nombre ,EMPRESAS.nombre AS empresa,PRACTICAS.horas,PRACTICAS.fecha,PRACTICAS.descripcion,TUTORES.nombre AS tutor FROM PRACTICAS 

INNER JOIN EMPRESAS ON PRACTICAS.id_empresa=EMPRESAS.id_empresa
INNER JOIN ESTUDIANTES ON PRACTICAS.id_estudiante=ESTUDIANTES.id_estudiante
INNER JOIN TUTORES ON PRACTICAS.id_tutor=TUTORES.id_tutor
WHERE PRACTICAS.estado=1